### ISSUE TITLE
down-gpus won't print the full cluster status if no gpus are down.

### ISSUE THREAD

**Issue by mpatsis** [cdt-data-science/cluster-scripts#24] opened 2020-03-03 15:45 UTC
down-gpus won't print the full cluster status if no gpus are down.
This happened in the ilcc-cluster when all the gpus were up.
It might be hard to replicate somewhere else but if you find the chance abd it's not too much of a hassle please check it.

If I manage to find time to fix it I will but please do so if anyone can and has some free time.

**Comment by RyanrDavies** [comment] 2020-03-05 10:47
I don't think that's a bug -- the expected behaviour of `down-gpus` is to list the gpus that are down, and if none are down it should just print "All up!" and exit.

I also don't think the behaviour of `down-gpus` should be changed to always print the cluster status as this seems like it would just create a duplicate of the `cluster-status` script -- open to discussion about this though.

If you want to get the full cluster status regardless of whether there are gpus down, you can run `cluster-status` directly.

**Closed** 2022-09-13 14:21 UTC
